version: '3.9'

services:
  db:
    image: bitnami/postgresql:16.2.0
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRESQL_DATABASE: postgres
    ports:
      - 5432:5432
    volumes:
      - ./migrations/0001_criar_tabela_clientes.sql:/docker-entrypoint-initdb.d/0001_cria_tabela_clientes.sql
