name: api_client
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  args: 2.4.0
  logging: 1.2.0
  mocktail: 1.0.3
  postgres: 2.6.4
  shelf: 1.4.0
  shelf_router: 1.1.3
  timezone: ^0.9.2

dev_dependencies:
  http: 1.1.0
  lints: 3.0.0
  test: 1.24.0
